# Generated by Django 4.2.11 on 2025-04-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do jogo')),
                ('genero', models.CharField(max_length=100, verbose_name='Gênero')),
                ('descricao', models.TextField(verbose_name='Descrição do jogo')),
                ('icone', models.ImageField(upload_to='icones/', verbose_name='Ícone')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='Imagem do banner')),
                ('imagem_extra_1', models.ImageField(blank=True, null=True, upload_to='extras/', verbose_name='Imagem extra 1')),
                ('imagem_extra_2', models.ImageField(blank=True, null=True, upload_to='extras/', verbose_name='Imagem extra 2')),
                ('imagem_extra_3', models.ImageField(blank=True, null=True, upload_to='extras/', verbose_name='Imagem extra 3')),
                ('processor_min', models.CharField(max_length=100, verbose_name='Processador mínimo')),
                ('gpu_min', models.CharField(max_length=100, verbose_name='Placa de vídeo mínima')),
                ('ram_min', models.CharField(max_length=50, verbose_name='Memória RAM mínima')),
                ('disk_min', models.CharField(max_length=50, verbose_name='Espaço em disco mínimo')),
                ('processor_rec', models.CharField(max_length=100, verbose_name='Processador recomendado')),
                ('gpu_rec', models.CharField(max_length=100, verbose_name='Placa de vídeo recomendada')),
                ('ram_rec', models.CharField(max_length=50, verbose_name='Memória RAM recomendada')),
                ('disk_rec', models.CharField(max_length=50, verbose_name='Espaço em disco recomendado')),
            ],
        ),
    ]
