# Generated by Django 4.2.11 on 2025-12-06 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='banner',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='disk_min',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='disk_rec',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='gpu_min',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='gpu_rec',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='icone',
            field=models.ImageField(upload_to='icones/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem_extra_1',
            field=models.ImageField(blank=True, null=True, upload_to='extras/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem_extra_2',
            field=models.ImageField(blank=True, null=True, upload_to='extras/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='imagem_extra_3',
            field=models.ImageField(blank=True, null=True, upload_to='extras/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='processor_min',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='processor_rec',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='ram_min',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='ram_rec',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
