# Generated by Django 4.2.11 on 2025-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0002_alter_jogo_banner_alter_jogo_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
