# Generated by Django 4.2.11 on 2025-06-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_django', '0003_profile_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='foto',
            new_name='foto_perfil',
        ),
    ]
